#Container Target Node
Vagrant.configure("2") do |config|
  # Use the official Ubuntu 22.04 LTS image
  config.vm.box = "ubuntu/jammy64"
  
  # Network configuration (Ports shifted to avoid conflicts)
  config.vm.network "forwarded_port", guest: 8080, host: 8084
  config.vm.network "forwarded_port", guest: 22, host: 2227, id: "ssh"
  config.vm.network "private_network", ip: "192.168.56.22"

  # Provider configuration
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end
end