Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8082, id: "jenkins"
  config.vm.network "forwarded_port", guest: 22, host: 2225, id: "ssh"
  config.vm.network "private_network", ip: "192.168.56.20"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false 
    vb.memory = 2048
    vb.cpus = 2
  end
end